run_analysis <- function()
{

  library("dplyr")
  ## In the first Step we try to read training data and integrate them all together and make
  ## one data frame which has following structure:
  ## Subject  Activity_Label  561 columns for features 128 columns for each body/total X,Y acc&Gyro
  ## -------  -------------   ------------------------ ------------------------------------------- 
  print("This project has 5 steps")
  print("Step 1:")
  ## Begining of Step 1 of the project
  ## Here the realted training files are read and stored in different data frames
  print("The subject_train.txt & y_train.txt & features.txt & X_train files are being read")
  subject=read.table("UCI HAR Dataset/train/subject_train.txt", col.names="subject")
  label=read.table("UCI HAR Dataset/train/y_train.txt",col.names="label")
  features_list =read.table("UCI HAR Dataset/features.txt")
  features_561 = read.table("UCI HAR Dataset/train/X_train.txt", col.names = features_list[,2])
  
  ## here not only we read the data also a column name is generated by adding an index to
  ## the name of the data, for example the 10th column of body_acc_x will be named: body_acc_x10
  ## we repeat this for all other body/total data as well
  print("The body_acc_x&y&z & body_gyro_x&y&z & toal_acc_x&y&zare of training data being read")
  body_acc_x_label = "body_acc_x1"
  for(i in 2:128) {body_acc_x_label = c(body_acc_x_label, paste("body_acc_x",as.character(i),sep=""))}
  body_acc_x=read.table("UCI HAR Dataset/train/Inertial Signals/body_acc_x_train.txt", col.names = body_acc_x_label)  

  body_acc_y_label = "body_acc_y1"
  for(i in 2:128) {body_acc_y_label = c(body_acc_y_label, paste("body_acc_y",as.character(i),sep=""))}
  body_acc_y=read.table("UCI HAR Dataset/train/Inertial Signals/body_acc_y_train.txt", col.names = body_acc_y_label)  

  body_acc_z_label = "body_acc_z1"
  for(i in 2:128) {body_acc_z_label = c(body_acc_z_label, paste("body_acc_z",as.character(i),sep=""))}
  body_acc_z=read.table("UCI HAR Dataset/train/Inertial Signals/body_acc_z_train.txt", col.names = body_acc_z_label)  

  body_gyro_x_label = "body_gyro_x1"
  for(i in 2:128) {body_gyro_x_label = c(body_gyro_x_label, paste("body_gyro_x",as.character(i),sep=""))}
  body_gyro_x=read.table("UCI HAR Dataset/train/Inertial Signals/body_gyro_x_train.txt", col.names = body_gyro_x_label)  
  
  body_gyro_y_label = "body_gyro_y1"
  for(i in 2:128) {body_gyro_y_label = c(body_gyro_y_label, paste("body_gyro_y",as.character(i),sep=""))}
  body_gyro_y=read.table("UCI HAR Dataset/train/Inertial Signals/body_gyro_y_train.txt", col.names = body_gyro_y_label)  
  
  body_gyro_z_label = "body_gyro_z1"
  for(i in 2:128) {body_gyro_z_label = c(body_gyro_z_label, paste("body_gyro_z",as.character(i),sep=""))}
  body_gyro_z=read.table("UCI HAR Dataset/train/Inertial Signals/body_gyro_z_train.txt", col.names = body_gyro_z_label)

  total_acc_x_label = "total_acc_x1"
  for(i in 2:128) {total_acc_x_label = c(total_acc_x_label, paste("total_acc_x",as.character(i),sep=""))}
  total_acc_x=read.table("UCI HAR Dataset/train/Inertial Signals/total_acc_x_train.txt", col.names = total_acc_x_label)  
  
  total_acc_y_label = "total_acc_y1"
  for(i in 2:128) {total_acc_y_label = c(total_acc_y_label, paste("total_acc_y",as.character(i),sep=""))}
  total_acc_y=read.table("UCI HAR Dataset/train/Inertial Signals/total_acc_y_train.txt", col.names = total_acc_y_label)  
  
  total_acc_z_label = "total_acc_z1"
  for(i in 2:128) {total_acc_z_label = c(total_acc_z_label, paste("total_acc_z",as.character(i),sep=""))}
  total_acc_z=read.table("UCI HAR Dataset/train/Inertial Signals/total_acc_z_train.txt", col.names = total_acc_z_label)  

  ## Here all data is read and the train_tidy_data is generated 
  ## next step we repeat similar steps to generate test_tidy_data
  train_tidy_data = data.frame(subject,label,features_561,body_acc_x,body_acc_y,body_acc_z,body_gyro_x,body_gyro_y,body_gyro_z,total_acc_x,total_acc_y,total_acc_z)
  
  print("The body_acc_x&y&z & body_gyro_x&y&z & toal_acc_x&y&zare of test data being read")
  ## following steps try to generate test_tidy_data
  subject=read.table("UCI HAR Dataset/test/subject_test.txt", col.names="subject")
  label=read.table("UCI HAR Dataset/test/y_test.txt",col.names="label")
  features_561 = read.table("UCI HAR Dataset/test/X_test.txt", col.names = features_list[,2])
  
  body_acc_x_label = "body_acc_x1"
  for(i in 2:128) {body_acc_x_label = c(body_acc_x_label, paste("body_acc_x",as.character(i),sep=""))}
  body_acc_x=read.table("UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt", col.names = body_acc_x_label)  
  
  body_acc_y_label = "body_acc_y1"
  for(i in 2:128) {body_acc_y_label = c(body_acc_y_label, paste("body_acc_y",as.character(i),sep=""))}
  body_acc_y=read.table("UCI HAR Dataset/test/Inertial Signals/body_acc_y_test.txt", col.names = body_acc_y_label)  
  
  body_acc_z_label = "body_acc_z1"
  for(i in 2:128) {body_acc_z_label = c(body_acc_z_label, paste("body_acc_z",as.character(i),sep=""))}
  body_acc_z=read.table("UCI HAR Dataset/test/Inertial Signals/body_acc_z_test.txt", col.names = body_acc_z_label)  
  
  body_gyro_x_label = "body_gyro_x1"
  for(i in 2:128) {body_gyro_x_label = c(body_gyro_x_label, paste("body_gyro_x",as.character(i),sep=""))}
  body_gyro_x=read.table("UCI HAR Dataset/test/Inertial Signals/body_gyro_x_test.txt", col.names = body_gyro_x_label)  
  
  body_gyro_y_label = "body_gyro_y1"
  for(i in 2:128) {body_gyro_y_label = c(body_gyro_y_label, paste("body_gyro_y",as.character(i),sep=""))}
  body_gyro_y=read.table("UCI HAR Dataset/test/Inertial Signals/body_gyro_y_test.txt", col.names = body_gyro_y_label)  
  
  body_gyro_z_label = "body_gyro_z1"
  for(i in 2:128) {body_gyro_z_label = c(body_gyro_z_label, paste("body_gyro_z",as.character(i),sep=""))}
  body_gyro_z=read.table("UCI HAR Dataset/test/Inertial Signals/body_gyro_z_test.txt", col.names = body_gyro_z_label)
  
  total_acc_x_label = "total_acc_x1"
  for(i in 2:128) {total_acc_x_label = c(total_acc_x_label, paste("total_acc_x",as.character(i),sep=""))}
  total_acc_x=read.table("UCI HAR Dataset/test/Inertial Signals/total_acc_x_test.txt", col.names = total_acc_x_label)  
  
  total_acc_y_label = "total_acc_y1"
  for(i in 2:128) {total_acc_y_label = c(total_acc_y_label, paste("total_acc_y",as.character(i),sep=""))}
  total_acc_y=read.table("UCI HAR Dataset/test/Inertial Signals/total_acc_y_test.txt", col.names = total_acc_y_label)  
  
  total_acc_z_label = "total_acc_z1"
  for(i in 2:128) {total_acc_z_label = c(total_acc_z_label, paste("total_acc_z",as.character(i),sep=""))}
  total_acc_z=read.table("UCI HAR Dataset/test/Inertial Signals/total_acc_z_test.txt", col.names = total_acc_z_label)  

  test_tidy_data = data.frame(subject,label,features_561,body_acc_x,body_acc_y,body_acc_z,body_gyro_x,body_gyro_y,body_gyro_z,total_acc_x,total_acc_y,total_acc_z)
  ## now that we have both train and test data in tidy shape we merge them together
  ## please be advised that since they have identical columns then by defualt common columns
  ## are getting merged together
  print("the test and training date are being merged")
  merge_tidy_data = merge(train_tidy_data,test_tidy_data, all=TRUE)
  print("merged tidy data is generated!")
  ## End of Step 1 of the project
  
  print("Step2:")
  ## Begining of Step 2 of the project
  ## here we exclude the mean and sdt columns plus activity_label and subject, and store them 
  ## to a new data frame
  x=names(merge_tidy_data)
  mean_sd_columns= c("subject","label") ##initial columns to be kept
  ## any column that has the partial sentence "mean" or "std" will be stored
  for (i in 1:length(x)) {if(grepl("mean", x[i]) | grepl("std", x[i])) mean_sd_columns=c(mean_sd_columns,x[i])}
  ## now the new data frame is generated from the stored column list
  mean_sd_data = merge_tidy_data[,mean_sd_columns]
  print("The mean and std columns are extracted for each measurement")
  ## End of Step 2 of the project
  
  print("Step3&4:")
  ## Begining of Step 3&4 of the project
  ## here the activity_label file is read and then mapped to label column of the data frame
  ## in other words numbers 1 to 6 are replaced by ativities lile WALKING, etc
  activity_labels = read.table("UCI HAR Dataset/activity_labels.txt", colClasses = "character")
  for(i in 1:nrow(mean_sd_data)) {mean_sd_data[i,2]=activity_labels[mean_sd_data[i,2],2]}
  ## Also please be advised that labeling of all variables have been done in former steps
  ## so this also addresses step 4 of the project as well.
  ## End of Step 3&4 of the project
  print("activity names and other labels are all updated")
  
  print("Step 5:")
  ## Begining of Step 5 of the project
  ## here for better presentation first we sort our data frame from previous step by subject
  ordered_data = arrange(mean_sd_data, subject)
  ## next we group it by subject and label (activity)
  dest = group_by(ordered_data, subject,label)
  ## finally we apply the mean function to each grouped data column
  result=dest%>%summarise_each(funs(mean))

  ## the final result is writtem to a .txt file
  write.table(result,"result.txt", row.names=FALSE)
  ## for better presentation the CSV file is also generated
  write.csv(result,"result.csv", row.names=FALSE)
  ## end of Step 5 and Project  
  print("Result is generated and stored into result.txt and result.csv")
}
